# Generated by Django 4.1.7 on 2023-03-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_at'], 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
